sudo: required
services:
  - docker

before_install:
  - docker build -t vinodchndrskr/react-test ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true vinodchndrskr/react-test npm run test

after-success:
  - docker build -t vinodchndrskr/multi-client ./client
  - docker build -t vinodchndrskr/multi-nginx ./nginx
  - docker build -t vinodchndrskr/multi-server ./server
  - docker build -t vinodchndrskr/multi-worker ./worker
  # Log into Docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -d "$DOCKER_ID" --password-stdin
  # Take those images and push them to Docker hub
  - docker push vinodchndrskr/multi-client
  - docker push vinodchndrskr/multi-nginx
  - docker push vinodchndrskr/multi-server
  - docker push vinodchndrskr/multi-worker